src/main/java/com/saldmy/entity/Test.java
package com.saldmy.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 * The {@code Test} class is a JavaBean, the objects of which store information about tests.
 *
 * @author Dmytro Salo
 */
public class Test implements Serializable {
	private int id;                              // db primary key
	private String title;
	private Subject subject;
	private Difficulty difficulty;
	private String language;
	private int numOfQuestions;
	private int timeLimit;                       // time to pass (in minutes)
	private int minPercentage;                   // minimum percentage of right answers to pass the test
	private int numOfSubmissions;                // number of people, submitted to the test
	private int numOfPasses;                     // number of people, passed the test
	private Date creationDate;
	private List<Question> questions;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Subject getSubject() {
		return subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Difficulty getDifficulty() {
		return difficulty;
	}

	public void setDifficulty(Difficulty difficulty) {
		this.difficulty = difficulty;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public int getNumOfQuestions() {
		return numOfQuestions;
	}

	public void setNumOfQuestions(int numOfQuestions) {
		this.numOfQuestions = numOfQuestions;
	}

	public int getTimeLimit() {
		return timeLimit;
	}

	public void setTimeLimit(int timeLimit) {
		this.timeLimit = timeLimit;
	}

	public int getNumOfSubmissions() {
		return numOfSubmissions;
	}

	public void setNumOfSubmissions(int numOfSubmissions) {
		this.numOfSubmissions = numOfSubmissions;
	}

	public int getNumOfPasses() {
		return numOfPasses;
	}

	public void setNumOfPasses(int numOfPasses) {
		this.numOfPasses = numOfPasses;
	}

	public int getMinPercentage() {
		return minPercentage;
	}

	public void setMinPercentage(int minPercentage) {
		this.minPercentage = minPercentage;
	}

	public Date getCreationDateObject() {
		return creationDate;
	}

	public String getCreationDate() {
		return new SimpleDateFormat("dd.MM.yyyy HH:mm").format(creationDate);
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public List<Question> getQuestions() {
		return questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	public void addQuestion(Question question) {
		questions.add(question);
	}

	public String getPassRate() {
		if (numOfSubmissions == 0) {
			return "-";
		} else {
			double passRate = (double) numOfPasses / numOfSubmissions;
			return String.format(Locale.US, "%.2f", passRate);
		}
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;
		Test test = (Test) o;
		return id == test.id && timeLimit == test.timeLimit && minPercentage == test.minPercentage && numOfSubmissions == test.numOfSubmissions && numOfPasses == test.numOfPasses && Objects.equals(title, test.title) && Objects.equals(subject, test.subject) && Objects.equals(difficulty, test.difficulty) && Objects.equals(language, test.language) && Objects.equals(creationDate, test.creationDate) && Objects.equals(questions, test.questions);
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, title, subject, difficulty, language, timeLimit, minPercentage, numOfSubmissions, numOfPasses, creationDate, questions);
	}

	@Override
	public String toString() {
		return "Test{" +
				"id=" + id +
				", title='" + title + '\'' +
				", subject=" + subject +
				", difficulty=" + difficulty +
				", language='" + language + '\'' +
				", timeLimit=" + timeLimit +
				", minPercentage=" + minPercentage +
				", numOfSubmissions=" + numOfSubmissions +
				", numOfPasses=" + numOfPasses +
				", creationDate=" + creationDate +
				'}';
	}

	public static class Question implements Serializable {
		private int id;
		private String questionText;
		private final List<Answer> answers;

		public Question() {
			this.answers = new ArrayList<>();
		}

		public String getQuestionText() {
			return questionText;
		}

		public String getPreview() {
			if (questionText.length() > 79) {
				return questionText.substring(0, 80).concat("...");
			} else {
				return questionText;
			}
		}

		public void setQuestionText(String questionText) {
			this.questionText = questionText;
		}

		public boolean isMultipleAnswers() {
			return answers.stream().filter(Answer::isCorrect).count() > 1;
		}

		public int getId() {
			return id;
		}

		public void setId(int id) {
			this.id = id;
		}

		public List<Answer> getAnswers() {
			return answers;
		}

		@Override
		public boolean equals(Object o) {
			if (this == o) return true;
			if (o == null || getClass() != o.getClass()) return false;
			Question question = (Question) o;
			return id == question.id && questionText.equals(question.questionText) && answers.equals(question.answers);
		}

		@Override
		public int hashCode() {
			return Objects.hash(questionText, id, answers);
		}

		@Override
		public String toString() {
			return "Question{" +
					"questionText='" + questionText + '\'' +
					", number=" + id +
					", answers=" + answers +
					'}';
		}

		public static class Answer implements Serializable {
			private int id;
			private boolean correct;
			private String text;

			public boolean isCorrect() {
				return correct;
			}

			public void setCorrect(boolean correct) {
				this.correct = correct;
			}

			public String getText() {
				return text;
			}

			public void setText(String text) {
				this.text = text;
			}

			public int getId() {
				return id;
			}

			public void setId(int id) {
				this.id = id;
			}

			@Override
			public boolean equals(Object o) {
				if (this == o) return true;
				if (o == null || getClass() != o.getClass()) return false;
				Answer answer = (Answer) o;
				return id == answer.id && correct == answer.correct && text.equals(answer.text);
			}

			@Override
			public int hashCode() {
				return Objects.hash(id, correct, text);
			}

			@Override
			public String toString() {
				return "Answer{" +
						"correct=" + correct +
						", text='" + text + '\'' +
						", number=" + id +
						'}';
			}
		}
	}
}

src/main/java/com/saldmy/entity/User.java
package com.saldmy.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.*;

/**
 * The {@code User} class is a JavaBean, the objects of which store information about users.
 *
 * @author Dmytro Salo
 */
public class User implements Serializable {
    private int id;
    private String email;
    private String password;
    private String firstName;
    private String lastName;
    private String status;
    private String role;
    private String preferredLanguage;
    private Date registrationDate;
    private List<TestResult> testResults = new ArrayList<>();

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getLocaleString() {
        if (Objects.equals(preferredLanguage, "English")) {
            return "en";
        } else if (Objects.equals(preferredLanguage, "Ukrainian")) {
            return "uk";
        } else {
            return null;
        }
    }

    public String getPreferredLanguage() {
        return preferredLanguage;
    }

    public void setPreferredLanguage(String preferredLanguage) {
        this.preferredLanguage = preferredLanguage;
    }

    public String getRegistrationDate() {
        return registrationDate != null
                ? new SimpleDateFormat("dd.MM.yyyy HH:mm").format(registrationDate) : null;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public void setTestResults(List<TestResult> testResults) {
        this.testResults = testResults;
    }

    public String getAveragePercentage() {
        int submittedTests = testResults.size();
        if (submittedTests == 0) {
            return "-";
        } else {
            long successfulTests = (int) testResults.stream()
                    .filter(TestResult::isSuccess)
                    .count();
            return String.format(Locale.US, "%.2f", (double) successfulTests / submittedTests);
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id && Objects.equals(email, user.email) && Objects.equals(password, user.password) && Objects.equals(firstName, user.firstName) && Objects.equals(lastName, user.lastName) && Objects.equals(status, user.status) && Objects.equals(registrationDate, user.registrationDate);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, email, password, firstName, lastName, status, registrationDate);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", status='" + status + '\'' +
                ", role='" + role + '\'' +
                ", preferredLanguage='" + preferredLanguage + '\'' +
                ", registrationDate=" + registrationDate +
                '}';
    }
}

src/main/webapp/secure/filterModal.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="f" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="my" %>
<c:set var="locale" value="${sessionScope.loggedUser.localeString}"/>
<f:setLocale value="${locale}"/>
<f:setBundle basename="text"/>
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel"
     aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="filterModalLabel"><f:message key="filter_results_by"/></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" action="${pageContext.request.contextPath}/controller" id="filterForm"
              class="mx-auto">
          <input type="hidden" name="command" value="filterTests">
          <input type="hidden" name="returnCommand" value="${param.command}">
          <p><f:message key="subjects"/>:</p>
          <c:forEach var="subject" items="${applicationScope.subjects}">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="subjects" value="${subject.id}"
                     id="subject${subject.id}"
              <c:forEach var="selectedSubjectId" items="${sessionScope.filteredSubjects}">
                ${selectedSubjectId == subject.id.toString() ? ' checked' : ''}
              </c:forEach>
              >
              <label class="form-check-label" for="subject${subject.id}">
                  ${locale == 'uk' ? subject.nameUk : subject.name}
              </label>
            </div>
          </c:forEach>
          <hr/>
          <p><f:message key="difficulties"/>:</p>
          <c:forEach var="difficulty" items="${applicationScope.difficulties}">
            <div class="form-check">
              <input class="form-check-input" type="checkbox" name="difficulties" value="${difficulty.id}"
                     id="difficulty${difficulty.id}"
              <c:forEach var="selectedDifficultyId" items="${sessionScope.filteredDifficulties}">
                ${selectedDifficultyId == difficulty.id.toString() ? ' checked' : ''}
              </c:forEach>
              >
              <label class="form-check-label" for="difficulty${difficulty.id}">
                  ${locale == 'uk' ? difficulty.nameUk : difficulty.name}
              </label>
            </div>
          </c:forEach>
          <hr/>
          <p><f:message key="languages"/>:</p>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="languages" value="English"
                   id="english"
            <c:forEach var="selectedLanguage" items="${sessionScope.filteredLanguages}">
              ${selectedLanguage == 'English' ? ' checked' : ''}
            </c:forEach>
            >
            <label class="form-check-label" for="english">
              <c:if test="${locale == 'en'}">English</c:if>
              <c:if test="${locale == 'uk'}"><my:ukrLangName language="English"/></c:if>
            </label>
          </div>
          <div class="form-check">
            <input class="form-check-input" type="checkbox" name="languages" value="Ukrainian"
                   id="ukrainian"
            <c:forEach var="selectedLanguage" items="${sessionScope.filteredLanguages}">
              ${selectedLanguage == 'Ukrainian' ? ' checked' : ''}
            </c:forEach>
            >
            <label class="form-check-label" for="ukrainian">
              <c:if test="${locale == 'en'}">Ukrainian</c:if>
              <c:if test="${locale == 'uk'}"><my:ukrLangName language="Ukrainian"/></c:if>
            </label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <a class="btn btn-danger"
           href="${pageContext.request.contextPath}/controller?command=showFoundTestsPage&page=1&new=true&sort=${param.sort}">
          <f:message key="reset"/>
        </a>
        <button type="submit" form="filterForm" class="btn btn-primary"><f:message key="do_filter"/></button>
      </div>
    </div>
  </div>
</div>

src/main/webapp/secure/paginationFooter.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<f:setLocale value="${sessionScope.loggedUser.localeString}"/>
<f:setBundle basename="text"/>
<br/><br/><br/>
<footer class="footer mt-auto py-3 bg-light fixed-bottom">
  <div class="container-md">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        <li class="page-item<c:if test="${requestScope.currentPage == 1}"> disabled</c:if>">
          <a class="page-link"
              <c:if test="${requestScope.sort == null}">
                href="${pageContext.request.contextPath}/controller?command=${param.command}&page=${requestScope.currentPage - 1}"
              </c:if>
              <c:if test="${requestScope.sort != null}">
                href="${pageContext.request.contextPath}/controller?command=${param.command}&page=${requestScope.currentPage - 1}&sort=${requestScope.sort}<c:if test="${param.reversed == true}">&reversed=true</c:if>"
              </c:if>
          >
            <f:message key="previous"/></a>
        </li>
        <c:forEach begin="1" end="${requestScope.pageQuantity}" var="pageNumber">
          <li class="page-item<c:if test="${requestScope.currentPage == pageNumber}"> active</c:if>">
            <a class="page-link"
                <c:if test="${requestScope.sort == null}">
                  href="${pageContext.request.contextPath}/controller?command=${param.command}&page=${pageNumber}"
                </c:if>
                <c:if test="${requestScope.sort != null}">
                  href="${pageContext.request.contextPath}/controller?command=${param.command}&page=${pageNumber}&sort=${requestScope.sort}<c:if test="${param.reversed == true}">&reversed=true</c:if>"
                </c:if>
            >
                ${pageNumber}
            </a>
          </li>
        </c:forEach>
        <li class="page-item<c:if test="${requestScope.currentPage == requestScope.pageQuantity}"> disabled</c:if>">
          <a class="page-link"
              <c:if test="${requestScope.sort == null}">
                href="${pageContext.request.contextPath}/controller?command=${param.command}&page=${requestScope.currentPage + 1}"
              </c:if>
              <c:if test="${requestScope.sort != null}">
                href="${pageContext.request.contextPath}/controller?command=${param.command}&page=${requestScope.currentPage + 1}&sort=${requestScope.sort}<c:if test="${param.reversed == true}">&reversed=true</c:if>"
              </c:if>
          >
            <f:message key="next"/></a>
        </li>
      </ul>
    </nav>
  </div>
</footer>

src/main/webapp/secure/question.jsp
<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="my" uri="/WEB-INF/myTagLib.tld" %>
<%@ taglib prefix="m" tagdir="/WEB-INF/tags" %>
<c:set var="locale" value="${sessionScope.loggedUser.localeString}"/>
<f:setLocale value="${locale}"/>
<f:setBundle basename="text"/>
<%
  System.out.println("jsp: question.jsp");
%>
<c:set var="root" value="${pageContext.request.contextPath}"/>
<c:set var="k" value="0"/>
<html>
<head>
  <title><f:message key="testing_in_progress"/></title>
  <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'/>
  <link rel="apple-touch-icon" sizes="180x180" href="${pageContext.request.contextPath}/static/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="${pageContext.request.contextPath}/static/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="${pageContext.request.contextPath}/static/favicon/favicon-16x16.png">
  <link rel="manifest" href="${pageContext.request.contextPath}/static/favicon/site.webmanifest">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
  <link href="${root}/static/css/sidebars.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous" async></script>
  <script src="${root}/static/js/sidebars.js" async></script>
</head>
<body>
  <main>
    <div class="d-flex flex-column align-items-stretch flex-shrink-0 bg-white" style="width: 380px;">
      <div class="list-group list-group-flush border-bottom scrollarea">
        <c:forEach items="${sessionScope.startedTest.questions}" var="question">
          <c:set var="k" value="${k + 1}"/>
          <button onclick="goTo(${k})" type="submit" form="answerForm"
                  class="list-group-item list-group-item-action py-3
                     <c:if test="${requestScope.currentQuestionNumber == k}">active </c:if>lh-tight"
                  <c:if test="${requestScope.currentQuestionNumber == k}">aria-current="true"</c:if>
          >
            <div class="d-flex w-100 align-items-center justify-content-between">
              <small>Question ${k}</small>
              <c:if test="${sessionScope.answerMap.get(question.id) != null}">
                <small class="text-success"><f:message key="answered"/></small>
              </c:if>
              <c:if test="${sessionScope.answerMap.get(question.id) == null}">
                <small class="text-warning"><f:message key="not_answered"/></small>
              </c:if>
            </div>
            <div class="col-10 mb-1 small">${question.preview}</div>
          </button>
        </c:forEach>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-4">
            <c:if test="${sessionScope.allAnswered == true}">
              <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#submitModal">
                <f:message key="submit_test"/>
              </button>
            </c:if>
            <c:if test="${sessionScope.allAnswered == false}">
              <button class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#submitModal">
                <f:message key="submit_test"/>
              </button>
            </c:if>
            <span class="font-monospace">&nbsp;</span>
            <span class="font-monospace <my:timerColor deadline="${sessionScope.deadline}"/>"
                  id="submitTimer"></span>
          </div>
        </div>
      </div>
      <div class="card-body">
        <br/>
        <p>${requestScope.currentQuestion.questionText}</p>
        <br/>
        <form id="answerForm" action="${root}/controller" method="post">
          <input type="hidden" name="command" value="receiveAnswer" id="command"/>
          <input type="hidden" name="questionId" value="${requestScope.currentQuestion.id}" id="questionId"/>
          <div class="list-group mx-0">
            <c:if test="${requestScope.currentQuestion.multipleAnswers == false}">
              <c:forEach items="${requestScope.currentQuestion.answers}" var="answer">
                <label class="list-group-item d-flex gap-2">
                  <input class="form-check-input flex-shrink-0" type="radio"
                         name="selectedAnswers"
                         value="${answer.id}"
                      <c:if test="${sessionScope.answerMap.get(requestScope.currentQuestion.id) != null}">
                        <c:set var="answerArray"
                               value="${sessionScope.answerMap.get(requestScope.currentQuestion.id)}"/>
                        <c:if test="${answerArray[0] == answer.id}"> checked</c:if>
                      </c:if>/>
                  <span>${answer.text}</span>
                </label>
              </c:forEach>
            </c:if>
            <c:if test="${requestScope.currentQuestion.multipleAnswers == true}">
              <c:forEach items="${requestScope.currentQuestion.answers}" var="answer">
                <label class="list-group-item d-flex gap-2">
                  <input class="form-check-input flex-shrink-0" type="checkbox"
                         name="selectedAnswers"
                         value="${answer.id}"
                      <c:if test="${sessionScope.answerMap.get(requestScope.currentQuestion.id) != null}">
                        <c:set var="answerArray"
                               value="${sessionScope.answerMap.get(requestScope.currentQuestion.id)}"/>
                        <c:forEach var="checkedAnswer" items="${answerArray}">
                          <c:if test="${checkedAnswer == answer.id}"> checked</c:if>
                        </c:forEach>
                      </c:if>/>
                  <span>${answer.text}</span>
                </label>
              </c:forEach>
            </c:if>
          </div>
        </form>
      </div>
      <div class="card-footer justify-content-center">
        <div class="btn-group" role="group">
          <button class="btn btn-outline-primary
                        <c:if test="${requestScope.currentQuestionNumber == 1}"> disabled</c:if>"
                  onclick="goTo(${requestScope.currentQuestionNumber - 1})" type="submit" form="answerForm">
            <f:message key="previous_m"/>
          </button>
          <button class="btn-outline-primary btn" disabled>
            <span class="text-dark">${requestScope.currentQuestionNumber}</span>
          </button>
          <button class="btn btn-outline-primary
                        <c:if test="${requestScope.currentQuestionNumber == sessionScope.startedTest.questions.size()}"> disabled</c:if>"
                  onclick="goTo(${requestScope.currentQuestionNumber + 1})" type="submit" form="answerForm">
            <f:message key="next_m"/>
          </button>
        </div>
      </div>
    </div>
  </main>
  <!-- Submit modal -->
  <div class="modal fade" id="submitModal" tabindex="-1" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="submitModalLabel"><f:message key="submit_test"/></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body text-center">
          <c:if test="${sessionScope.allAnswered == true}">
            <p><f:message key="submit_test_msg"/></p>
            <p><f:message key="continue?"/></p>
          </c:if>
          <c:if test="${sessionScope.allAnswered == false}">
            <p class="fw-semibold"><f:message key="not_all_questions_ans"/></p>
            <p><f:message key="still_continue?"/></p>
          </c:if>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><f:message key="cancel"/></button>
          <button <c:if test="${sessionScope.allAnswered == true}">class="btn btn-primary"</c:if>
                  <c:if test="${sessionScope.allAnswered == false}">class="btn btn-danger"</c:if>
                  type="submit" form="answerForm" onclick="submitTest()">
            <f:message key="submit_test"/>
          </button>
        </div>
      </div>
    </div>
  </div>
  <script>
      const countDownDate = new Date(${sessionScope.deadline});
      const x = setInterval(function () {
          const now = new Date().getTime();
          const distance = countDownDate - now;

          let hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
          let minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
          let seconds = Math.floor((distance % (1000 * 60)) / 1000);
          
          if (hours < 10) {
              hours = "0" + hours;
          }
          if (minutes < 10) {
              minutes = "0" + minutes;
          }
          if (seconds < 10) {
              seconds = "0" + seconds;
          }
          if (hours !== "00") {
              document.getElementById("submitTimer").innerHTML = hours + ":"
                  + minutes + ":" + seconds;
          } else {
              document.getElementById("submitTimer").innerHTML = minutes + ":" + seconds;
          }
          if (distance < 0) {
              submitTest();
          }
      }, 1000);
  </script>
  <script async>
      async function goTo(questionToGo) {
          await new Promise(resolve => setTimeout(resolve, 150));
          window.location.href = "${root}/controller?command=serviceTest&question=" + questionToGo;
      }

      async function submitTest() {
          await new Promise(resolve => setTimeout(resolve, 150));
          post("${root}/controller", {command: "submitTest"});
      }
      
      function post(path, params) {
          const form = document.createElement('form');
          form.method = "POST";
          form.action = path;

          for (const key in params) {
              if (params.hasOwnProperty(key)) {
                  const hiddenField = document.createElement('input');
                  hiddenField.type = 'hidden';
                  hiddenField.name = key;
                  hiddenField.value = params[key];

                  form.appendChild(hiddenField);
              }
          }

          document.body.appendChild(form);
          form.submit();
      }
  </script>
</body>
</html>